### ISSUE TITLE
Project status and future ?

### ISSUE THREAD

**Issue by zeitounator** [jmespath/jmespath.py#192]
Hi,

It looks like this project has not been updated for a while: last commit is 11 months old, there are several PRs and tickets that did not get any responses/updates. As an example, as an ansible user I am very interested in #158 and waiting for a status update for more than a year. Unfortunately, it seems to be the same on other repository for other languages.

Is this project still alive ? What is it's exact status ? Can we get some info about what its future might be ?

As an ansible user, I use JMESpath through the json_query filter and I have based a lot of my data queries on it. I'd like to know if can go on or if I should already look for an alternative in case this lib dies.

I can perfectly understand if the original maintainers have no more time to devote to such a time consuming project. But please tell us so we can organize ourselves and either wait for your next release, or start a discussion with you on how the community can help, or fork and continue the project somewhere else, or move to an alternative solution....

Hoping for a reply, regards,

**Comment by jamesls** [comment]
Hi, I have an update on one of the other jmespath repos: https://github.com/jmespath/jmespath.site/issues/65#issuecomment-592613602

But to answer your questions directly:

> Is this project still alive ? What is it's exact status ? Can we get some info about what its future might be ?

For a long while, this project was on hold.  Initially it was just freezing the spec so that libraries and tooling could stabilize, but that time has long passed.

However, I now have time to work on jmespath again.  I'm in the process of going through all the various issues across the repos, but it's going to take a while.

Once I do get things in a back-to-life state, I will also start trying to organize things so I can have other people help out the maintenance of the various libraries.  I'll take a look at #158 shortly.

Thanks for understanding, and I look forward to JMESPath development ramping up again!
