### ISSUE TITLE
'pip install --upgrade awscli' makes jp command fail

### ISSUE THREAD

**Issue by mbailey** [jmespath/jmespath.py#82]
$ jp -h
bash: /usr/local/bin/jp: /Users/jamessar/.virtualenvs/a16cce535ca9ee79/bin/python: bad interpreter: No such file or directory

**Comment by lsh-0** [comment]
A great big "me too" - any insight?

**Comment by lsh-0** [comment]
vim `which jp` and then modifying the shbang to something sane like `#!/usr/bin/env python` makes it work.

**Comment by mbailey** [comment]
I traced the issue back to a python package. Is this something you could fix @jamesls?

$ wget https://pypi.python.org/packages/py2.py3/j/jmespath/jmespath-0.7.1-py2.py3-none-any.whl#md5=1977b145d6923911ee1088d0b0221b8a
$ unzip -q jmespath-0.7.1-py2.py3-none-any.whl && head -1 jmespath-0.7.1.data/scripts/jp
#!/Users/jamessar/.virtualenvs/a16cce535ca9ee79/bin/python

**Comment by jamesls** [comment]
To give some background on what's going on here, in the last release I moved the `jp` script over to `jp.py`.  The other languages that provide an executable have been following that convention, e.g. `jp.rb`, `jp.php`, `jp.js`, etc.

The other main reason I'm doing this is because there will be a separate `jp` executable as a standalone project, coming soon.

Does switching over to using `jp.py` work for you?

**Comment by lsh-0** [comment]
Works for me. I'll test it Monday.

**Comment by mbailey** [comment]
It seems to work for me (I've not used it in anger yet). Thanks

Are you going to remove the broken jp executable in the next release?

**Comment by weilu** [comment]
This issue still persists in 0.9.2. It's botocore that uses it and my app in turn uses botocore. It broken the rpm package due to the this path issue. @jamesls can we remove the broken executable and have a new release like @mbailey suggested?

**Comment by weilu** [comment]
Looks like an old bug that's back in 0.9.2. According to  #90 0.9.1 is still good.

**Comment by SgtCoDFish** [comment]
We've seen similar to this today as this project is a dependency of boto3/botocore. We fixed by adding `jmespath==0.9.1` to our own project's `requirements.txt` for now.

I believe this surfaced for us because we're packaging everything into one RPM. The reference to the local virtualenv got added in as a dependency to our RPM automatically.

**Comment by astratto** [comment]
We've just hit the same issue @SgtCoDFish.

@jamesls, do you want a new issue to be raised or should this one be reopened?
